### PR TITLE
Parameterized subprocesses and POD --help/--man changes.  

### PR DESCRIPTION
**Pull request by alanhoyle**

### CODE REVIEW

**Review by ckandoth — COMMENTED** [review]
Thanks @alanhoyle. Can you rebase your branch on the latest `main`? Email me if you need help. It may be tricky because I only partially merged your previous PR. I excluded your commit with the test data, because I created my own test data for --vep-custom that would work on Travis-CI.

**Comment by alanhoyle** [comment]
Keeping updated to upstream seems like a real pain.  I think the easiest thing for me to do is to blow away my fork from github, recreate a new fork, pull that locally, and copy over my changes into that.

**Comment by ckandoth** [comment]
Ok, sorry about that @alanhoyle. I'll close this PR without merging.

**Comment by alanhoyle** [comment]
No worries!  I really just need to learn to get better at git....  ;-)

**Pull request closed without merging**
