### PR TITLE
Set executable bit on scripts

### PR DESCRIPTION
**Pull request by sambrightman**

### CODE REVIEW

**Comment by ckandoth** [comment]
Thanks Sam. But I want to make users follow the good practice of specifying the version of `perl` being used. Either in lab notes they keep, or the log files generated by their pipelines. For example:

`/opt/CentOS_6/perl/perl-5.22.0/bin/perl /opt/CentOS_6/vcf2maf/v1.6.7/vcf2maf.pl --input-vcf ...`

is more informative to keep in your notes, rather than:

`./vcf2maf.pl --input-vcf ...`

For users that want the convenience of the latter, I have added `#!/usr/bin/env perl` to each script, so they can simply set executable bits locally.

**Comment by sambrightman** [comment]
Isn't it better to leave the environment management up to the user? There are many ways to manage versions, and trying to make an executable path appear somewhere is rather a weak one. It doesn't even prevent you from running an arbitrary perl with no path.

**Comment by ckandoth** [comment]
Environment management is entirely up to users. Not setting executable bits, makes them less likely to use the scripts in a way that I consider bad practice. But without forcefully imposing my subjective opinion on the matter.

**Comment by sambrightman** [comment]
At the moment I run `perl vcf2maf.pl` with no path or version showing anywhere. If I've configured my environment properly to choose the perl version, the point of the shebang line - in combination with an executable bit - is to make this more convenient (especially where you might want to `exec` the `vcf2maf.pl` itself, for example). Someone who doesn't bother with their perl environment can do exactly the same, right? It isn't even hard for them to commit the practice that you dislike.

How about setting the executable bit but also printing the Perl and `vcf2maf` at startup? Then it doesn't matter how you run it, you are definitely going to see/log the version.

**Comment by ckandoth** [comment]
> It isn't even hard for them to commit the practice that you dislike.

I don't want to make it hard.

Another reason is my `compulsive desire` to not set executable bits on source code. It's the responsibility of a package manager to place the script in a `$PATH` folder, remove the `.pl` suffix, and set executable bits. At some point I want to implement this, but it needs more thought. A package manager creates it's own `barriers to access` for novice users without `sudo` rights.

For now, I'm leaning to agree with you. And we've spent too much more time on this, than it deserves. I'll make a decision on the weekend.

**Comment by ckandoth** [comment]
I decided not to do this. Users that want an executable version of these scripts, can run `setup.py` as described in [mskcc/cmo](https://github.com/mskcc/cmo#for-external-users) for external users. This gives them direct access to CLI commands like `cmo_vcf2maf` and `cmo_maf2maf`.

**Comment by sambrightman** [comment]
I don't find a multi-step process which depends on another separate tool and a different language to simplify running a simple script.

This thread is frankly bizarre, and substantially off-putting towards contributions in general.

**Comment by ckandoth** [comment]
Sorry I couldn't be more flexible. I continue to encourage [more important contributions](https://github.com/mskcc/vcf2maf/pulls?q=is%3Amerged%20-author%3Ackandoth).

**Pull request closed without merging**
