### PR TITLE
Update uniprot isoform list to only have hg19

### PR DESCRIPTION
**Pull request by inodb**
There were several transcripts that were not in the ensembl hg19 transcript
dump. This assigns an ensembl transcript for 281 of the 307 hugo symbols (the
other ones don't have a good alternative in hg19 dump). None of these 307 are
particularly import genes for our purposes. See analysis:

https://github.com/inodb/genome-nexus-importer/blob/one-geneid-per-hgnc/notebooks/ensembl_identifiers.ipynb

For each of these genes we pick in this order:

1. the one assigned by hgnc website
2. the one assigned with is_canonical is true in ensembl data dump
3. the longest protein
4. the latest gene_stable_id

See the google docs for all the assignments (ensembl_canonical_transcripts vs
uniprot_canonical_transcript):

https://docs.google.com/spreadsheets/d/12o3OhlT-K0XQHW6T_kRxCaWIwwUyYlUY5OZkQP9wwns/edit#gid=934483692

### CODE REVIEW

**Comment by inodb** [comment]
[DO NOT MERGE] - just noticed number of lines changes is off compared to my numbers, maybe i was using a slightly older version of uniprot isoform list. Will check

**Comment by inodb** [comment]
Ah yes, was on 1.6.14 instead of 1.6.16, will update

**Comment by inodb** [comment]
Ok updated, 281 changed lines now, which makes sense with numbers above

**Comment by inodb** [comment]
@jjgao ☝️

**Comment by inodb** [comment]
Fine to merge now, I added a new list for uniprot for just hg19

**Comment by ckandoth** [comment]
@inodb I looked through your python notebook, but couldn't figure this out - why call it `hg19`? hg19 is a reference genome version, not a transcript database version.

**Comment by ckandoth** [comment]
@inodb I renamed the file to `isoform_overrides_uniprot_from_biomart_91` and added it to vcf2maf v1.6.16, so you can reference this as https://github.com/mskcc/vcf2maf/blob/v1.6.16/data/isoform_overrides_uniprot_from_biomart_91

**Comment by inodb** [comment]
Thanks! Yes as discussed on slack - using biomart v91 as filename makes more sense. Thanks for updating!

**Pull request merged**
